#!/bin/sh

# change directory to src
cd src
# run tests
make tests

# based on the output code $? (0 is OK else error)
if [ $? -ne 0 ]; then
	cat < "This commit is aborted because make tests failed." 
	exit 1
fi
